#!/usr/local/bin/php
<?php

include "vendor/autoload.php";

ini_set('date.timezone', 'Europe/Moscow');

$application = new Basis\Application($root);

try {
    array_shift($argv);
    $job = $argv ? array_shift($argv) : 'module.meta';

    $result = $application->dispatch($job, $argv ?: []);
    if ($result) {
        if (!is_object($result) || count(get_object_vars($result))) {
            echo json_encode($result), PHP_EOL;
        }
    }

    $application->get(Basis\Event::class)->fireChanges($job);
    $application->finalize();

} catch (Exception $e) {
    var_dump([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
