#!/usr/local/bin/php
<?php

ini_set('date.timezone', 'Europe/Moscow');

include "vendor/autoload.php";

use Basis\Application;
use Basis\Event;

$app = new Application($root);

try {
    array_shift($argv);
    $job = $argv ? array_shift($argv) : 'module.meta';
    $result = $app->dispatch($job, $argv ?: []);
    if ($result) {
        if (!is_object($result) || count(get_object_vars($result))) {
            echo json_encode($result), PHP_EOL;
        }
    }

    $app->get(Event::class)
        ->fireChanges($job);

    $app->finalize();

} catch (Exception $e) {
    throw $e;
    var_dump([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
