#!/usr/local/bin/php
<?php

include "vendor/autoload.php";

ini_set('date.timezone', 'Europe/Moscow');

Swoole\Runtime::enableCoroutine();

$application = new Basis\Application();
$server = $application->get(Swoole\HTTP\Server::class);
$logger = $application->get(Psr\Log\LoggerInterface::class);

$server->on('request', function ($request, $response) use ($logger) {
    $application = new Basis\Application();
    try {
        $application->get(Basis\Http::class)->swoole($request, $response);
        $application->finalize();
    } catch (Throwable $e) {
        $traceString = implode(PHP_EOL, $e->getTraceAsString());
        $logger->info($e->getMessage() . PHP_EOL . $traceString);
        $application->finalize();
    }
});

$server->start();
