#!/bin/bash

if [ -d "/app" ]; then
    cp -r /app/js/ /var/www/html/public
    cp -r /app/php /var/www/html
    cp -r /app/styl /var/www/html/public
    rm -rf /app
fi

composer dump-autoload --classmap-authoritative

mkfifo /var/application.log
chmod go+rw /var/application.log

tail -f /var/application.log&

php console module.bootstrap

if [ -f "php/Job/Background.php" ]; then
    ./loop php console module.process job=module.background iterations=1024&
fi

if [ "$SERVICE_EXECUTOR" != "false" ]; then
    ./loop php console module.process job=module.execute iterations=1024&
fi

./loop php console module.tick&

apache2-foreground > /dev/null