#!/bin/bash

if [ ! -d "var" ]; then
    mkdir var
fi

if [ ! -f "var/log" ]; then
    mkfifo var/log
    chmod go+rw var/log
fi

if [ ! -f "var/telemetry" ]; then
    mkfifo var/telemetry
    chmod go+rw var/telemetry
fi

tail -f var/log&

if [ "$BASIS_ENVIRONMENT" != "dev" ]; then
    ./composer.phar dump-autoload --classmap-authoritative
else
    ./composer.phar dump-autoload
fi

apache2-foreground& > /dev/null

php console module.starter
