#!/usr/local/bin/php
<?php

$script = array_shift($argv);
$version = array_shift($argv);
$commit = array_shift($argv);
$branch = array_shift($argv);

if (file_exists('version.php')) {
    $file = include('version.php');
    if (is_array($file)) {
        $branch = $file['ref_name'];
        $commit = $file['short_sha'];
        $version = $file['version'] ?: 'dev-' . $branch;
    }
}

if (strpos($version, '-') !== false) {
    $version = 'dev-' . $branch . ':' . $commit;
}
compose('/var/www/html/composer.json', function ($data) use ($version) {
    $data->version = $version;
});

function compose($path, $callback) {
    $json = file_get_contents($path);
    $data = json_decode($json);
    $callback($data);
    $json = json_encode($data, JSON_UNESCAPED_SLASHES);
    file_put_contents($path, $json);

    echo 'version is ', $data->version, PHP_EOL;
}
